### ISSUE TITLE
Cancellation for named pipes is not working if WaitForConnectionAsync has started

### ISSUE THREAD

**Issue by msyuyigit** [jacqueskang/IpcServiceFramework#47]
Fixing cancellation for named pipes. CancellationToken doesn't stop WaitForConnectionAsync if the connection is not opened with async option. In .Net standard, that parameter is not present in any of the constructors. This results in leak of threads in named pipes. Solution is handling things manually.

See:
https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeserverstream.waitforconnectionasync?view=netframework-4.7.2
"Cancellation requests using the cancellation token will only work if the NamedPipeServerStream object was created with a pipe option value of PipeOptions.Asynchronous or if the cancellation occurs before the WaitForConnectionAsync method is called."

CodeFix for NamedPipeIpcServiceEndpoint.cs:

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.IO.Pipes;
using System.Threading;
using System.Threading.Tasks;

namespace JKang.IpcServiceFramework.NamedPipe
{
    public class NamedPipeIpcServiceEndpoint<TContract> : IpcServiceEndpoint<TContract>
        where TContract : class
    {
        private readonly ILogger<NamedPipeIpcServiceEndpoint<TContract>> _logger;
        private readonly NamedPipeOptions _options;

        public NamedPipeIpcServiceEndpoint(string name, IServiceProvider serviceProvider, string pipeName)
            : base(name, serviceProvider)
        {
            PipeName = pipeName;

            _logger = serviceProvider.GetService<ILogger<NamedPipeIpcServiceEndpoint<TContract>>>();
            _options = serviceProvider.GetRequiredService<NamedPipeOptions>();
        }

        public string PipeName { get; }

        public override async Task ListenAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            for (int i = 0; i < _options.ThreadCount; i++)
            {
                var thread = new Thread(StartServerThread);
                thread.Start(cancellationToken);
            }

            _logger.LogDebug($"Endpoint '{Name}' listening on pipe '{PipeName}'...");

            // Wait till cancellationToken is signalled
            await Task.Delay(-1, cancellationToken);
        }

        private void StartServerThread(object obj)
        {
            var token = (CancellationToken)obj;
            try
            {
                var server = new NamedPipeServerStream(PipeName, PipeDirection.InOut, _options.ThreadCount);
                var tokenRegistration = token.Register(() => server.Dispose());
                if (token.IsCancellationRequested)
                {
                    throw new TaskCanceledException("Operation canceled");
                }

                server.BeginWaitForConnection(
                    async ar => await this.StreamCallback(server, ar, tokenRegistration, token), null);
            }
            catch when (token.IsCancellationRequested)
            {
            }
        }

        private async Task StreamCallback(
            NamedPipeServerStream stream,
            IAsyncResult ar,
            CancellationTokenRegistration tokenRegistration,
            CancellationToken cancellationToken)
        {
            try
            {
                stream.EndWaitForConnection(ar);
                await ProcessAsync(stream, _logger, cancellationToken);
            }
            catch when (cancellationToken.IsCancellationRequested)
            {
            }
            finally
            {
                tokenRegistration.Dispose();
                stream.Close();
                stream.Dispose();

                if (!cancellationToken.IsCancellationRequested)
                {
                    // Create a new stream since this one is done
                    var newThread = new Thread(StartServerThread);
                    newThread.Start(cancellationToken);
                }
            }
        }
    }
}

**Comment by msyuyigit** [comment]
BTW, if you can give me access to create pull requests, I can do that next time as well.

**Comment by jacqueskang** [comment]
@msyuyigit Thank you for raising the issue. Normally everyone can create PR in this repository. Isn't that the case?

**Comment by msyuyigit** [comment]
When I try to push to a local branch, I get the following error:
remote: Permission to jacqueskang/IpcServiceFramework.git denied to msyuyigit.
fatal: unable to access 'https://github.com/jacqueskang/IpcServiceFramework.git/': The requested URL returned error: 403

**Comment by jacqueskang** [comment]
Could you please try again

**Comment by msyuyigit** [comment]
Same error.

**Comment by msyuyigit** [comment]
Looks like the code I sent has an issue as well. Getting the following exception in some cases. Investigating:

Unhandled Exception: System.IO.IOException: The pipe is being closed
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnection()
   at System.IO.Pipes.NamedPipeServerStream.<>c.<WaitForConnectionAsync>b__17_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at JKang.IpcServiceFramework.NamedPipe.NamedPipeIpcServiceEndpoint`1.StreamCallback(NamedPipeServerStream stream, IAsyncResult ar, CancellationTokenRegistration tokenRegistration, CancellationToken cancellationToken)
   at JKang.IpcServiceFramework.NamedPipe.NamedPipeIpcServiceEndpoint`1.<>c__DisplayClass7_1.<<StartServerThread>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by msyuyigit** [comment]
Looks like this is also caused by another issue in named pipes client. We need to call WaitForPipeDrain(); in NamedPipeClientStream after we're done reading as a client:
https://stackoverflow.com/questions/9175417/pipe-is-being-closed-exception

**Comment by msyuyigit** [comment]
The fix for the above issue is the following:

NamedPipeIpcServiceClient.cs - Add the following method:

        protected override void DisconnectFromServer(Stream stream)
        {
            if (stream is NamedPipeClientStream namedPipeClientStream)
            {
                stream.Flush();
                namedPipeClientStream.WaitForPipeDrain();
            }
        }

In IpcServiceClient - Make sure this is called before stream is closed:

        private async Task<IpcResponse> GetResponseAsync(IpcRequest request, CancellationToken cancellationToken)
        {
            using (Stream client = await ConnectToServerAsync(cancellationToken))
            using (var writer = new IpcWriter(client, _serializer, leaveOpen: true))
            using (var reader = new IpcReader(client, _serializer, leaveOpen: true))
            {
                // send request
                await writer.WriteAsync(request, cancellationToken).ConfigureAwait(false);

                // receive response
                var response = await reader.ReadIpcResponseAsync(cancellationToken).ConfigureAwait(false);

                // disconnect
                this.DisconnectFromServer(client);

                return response;
            }
        }

**Comment by jacqueskang** [comment]
@msyuyigit Seems that NamedPipeServerStream does have a constructor taking PipeOptions.Asynchronous, should that be enough to fix the issue?  (see PR #48)

**Comment by msyuyigit** [comment]
Yes, this should work as well.
